version: '3'

services:
  api:
    container_name: "ii1302_api"
    build: .
    environment:
      - "PORT=3000"
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: "npm start"
    depends_on:
      - "db"


  db:
    container_name: "ii1302_db"
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ii1302
    volumes:
      - ./:/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    working_dir: /data
    restart: unless-stopped